apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixel-art
  namespace: pixel-art
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixel-art
  template:
    metadata:
      labels:
        app: pixel-art
    spec:
      containers:
        - name: pixel-art
          image: pixel-art:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
